lplayer cleanup

diff --git a/lplayer/lplayer b/lplayer/lplayer
--- a/lplayer/lplayer
+++ b/lplayer/lplayer
@@ -13,13 +13,17 @@
 #  DEFAULTS
 #
 
-VERSION="1.1"
-QUEUE_FILE=/tmp/lplayerqueue
-CHANNELS="2"
-SAMPLERATE="48000"
-PLAYER=mplayer
-PLAYER_OPTIONS="-nocache -nolirc -vc null -vo null -loop 0 \
--af resample=${SAMPLERATE} -ao pcm:nowaveheader:file=${QUEUE_FILE}"
+readonly _VERSION_='1.2-dev'
+
+readonly _PLAYER=mplayer
+
+_FILENAME=''
+_QUEUE_FILE=/tmp/lplayerqueue
+_CHANNELS='2'
+_SAMPLERATE='48000'
+_PLAYER_OPTIONS="-nocache -nolirc -vc null -vo null -loop 0
+                 -af resample=${_SAMPLERATE}
+                 -ao pcm:nowaveheader:file=${_QUEUE_FILE}"
 
 
 #
@@ -27,58 +31,67 @@ PLAYER_OPTIONS="-nocache -nolirc -vc null -vo null -loop 0 \
 #
 
 help_message () { 
-	#
-	# Shows help message.
-	#
-	# Returns:
-	#     String message to standard output
-	#
-	echo "lplayer - gapless loop player (using mplayer)."
-	echo "Usage:"
-	echo "  lplayer [options] filename"
-	echo 
-	echo "Options:"
-	echo "  -p, --playlist <filename>        use specified player"
-	echo "  -o, --player-options <options>   set player options"
-	echo "      --channels <number>          set number of channels"
-	echo "      --samplerate <number>        set samplerate"
-	echo "  -h, --help                       show this help"
-	echo "  -v, --version                    show version number"
+  #
+  # Shows help message.
+  #
+  # Globals:
+  #     None.
+  #
+  # Arguments:
+  #     None.
+  #
+  # Returns:
+  #     String message to standard output
+  #
+  echo 'lplayer - gapless loop player (using mplayer).'
+  echo 'Usage:'
+  echo '  lplayer [options] filename'
+  echo 
+  echo 'Options:'
+  echo '  -p, --playlist <filename>        use specified player'
+  echo '  -o, --player-options <options>   set player options'
+  echo '      --channels <number>          set number of channels'
+  echo '      --samplerate <number>        set samplerate'
+  echo '  -h, --help                       show this help'
+  echo '  -V, --version                    show version number'
 }
 
 version_message() {
-	#
-	# Shows version message.
-	#
-	# Args:
-	#     version (str) - Version number.
-	#
-	# Returns:
-	#     String message to standard output
-	#
-	local version
-	local "${@}"
-
-	echo "lplayer "${version};
-	echo
-	echo "Copyright (c) 2013 Maciej Żok"
-	echo "MIT License (http://opensource.org/licenses/MIT)"
+  #
+  # Shows version message.
+  #
+  # Globals:
+  #     _VERSION_ (str) -Version number.
+  #
+  # Arguments:
+  #     None.
+  #
+  # Returns:
+  #     String message to standard output
+  #
+  echo "lplayer ${_VERSION_}"
+  echo
+  echo 'Copyright (c) 2014 Maciej Żok'
+  echo 'MIT License (http://opensource.org/licenses/MIT)'
 }
 
 error_message() {
-	#
-	# Shows error message.
-	#
-	# Args:
-	#     msg (str) - Error message.
-	#
-	# Returns:
-	#     String message to err output.
-	#
-	local msg
-	local "${@}"
+  #
+  # Shows error message.
+  #
+  # Globals:
+  #     None.
+  #
+  # Arguments:
+  #     msg (str) - Error message.
+  #
+  # Returns:
+  #     String message to err output.
+  #
+  local msg
+  local "$@"
 
-	echo "Error: "${msg}"." 1>&2
+  echo "Error: ${msg}." 1>&2
 }
 
 
@@ -87,92 +100,115 @@ error_message() {
 #
 
 parse_args() {
-	#
-	# Parses script parameters.
-	#
-	# Args:
-	#     params (str) - Script params.
-	#
-	# Returns:
-	#     String message or nothing.
-	#
-	if [[ $# -eq 0 ]]; then
-		error_message msg="no audio file"
-		exit 1
-	else
-		while [[ $1 == -* ]]; do
-			case "$1" in
-				-h|--help|-\?)
-					help_message
-					exit 0;;
+  #
+  # Parses script parameters.
+  #
+  # Globals:
+  #     _CHANNELS (str) - Number of channels.
+  #     _FILENAME (str) - Name of music file.
+  #     _PLAYER_OPTIONS (str) - Music player command options.
+  #     _SAMPLERATE (str) - Sample rate.
+  #
+  # Arguments:
+  #     Script params.
+  #
+  # Returns:
+  #     String message or nothing.
+  #
+  if [[ $# -eq 0 ]]; then
+    error_message msg='no audio file'
+    exit 1
+  else
+    while [[ $1 == -* ]]; do
+      case "$1" in
+        -h|--help|-\?)
+          help_message
+          exit 0
+          ;;
 
-				-v|--version|-\?)
-					version_message version=${VERSION}
-					exit 0;;
+        -V|--version|-\?)
+          version_message
+          exit 0
+          ;;
 
-				-p|--playlist)
-					PLAYER_OPTIONS="${PLAYER_OPTIONS} -playlist"
-					shift 2;;
+        -p|--playlist)
+          _PLAYER_OPTIONS="${_PLAYER_OPTIONS} -playlist"
+          shift 2
+          ;;
 
-				-o|--player-options) 
-					if [[ $# -gt 1 ]]; then
-						OPTIONS=${PLAYER_OPTIONS} $2
-						shift 2
-					else
-						error_message msg="no player options specified"
-						exit 1
-					fi;;
+        -o|--player-options) 
+          if [[ $# > 1 ]]; then
+            _PLAYER_OPTIONS="${_PLAYER_OPTIONS} $2"
+            shift 2
+          else
+            error_message msg='no player options specified'
+            exit 1
+          fi
+          ;;
 
-				--channels)
-					CHANNELS=$2
-					shift 2;;
+        --channels)
+          _CHANNELS="$2"
+          shift 2
+          ;;
 
-				--samplerate)
-					SAMPLERATE=$2
-					shift 2;;
+        --samplerate)
+          _SAMPLERATE="$2"
+          shift 2
+          ;;
 
-				-*)
-					error_message msg="invalid option: ${1}"
-					help_message
-					exit 1;;
-			esac
-		done
-	fi
+        -*)
+          error_message msg="invalid option: $1"
+          help_message
+          exit 1
+          ;;
+      esac
+    done
+
+    _FILENAME="${@: -1}"  # filename is last argument
+  fi
 }
 
 make_queue() {
-	#
-	# Creates new queue.
-	#
-	# Args:
-	#     queue (str) - Queue file name.
-	#
-	local queue
-	local "${@}"
-
-	[[ -e ${queue} ]] && rm ${queue}
-	mkfifo ${queue}
+  #
+  # Creates new queue.
+  #
+  # Globals:
+  #     _QUEUE_FILE (str) - Name of queue file.
+  #
+  # Arguments:
+  #     None.
+  #
+  # Returns:
+  #     None.
+  #
+  [[ -e ${_QUEUE_FILE} ]] && rm ${_QUEUE_FILE}
+  mkfifo ${_QUEUE_FILE}
 }
 
 play() {
-	#
-	# Plays file in loop.
-	#
-	# Args:
-	#     file (str) - s.
-	#
-	# Returns:
-	#     String message or nothing.
-	#
-	local file
-	local "${@}"
+  #
+  # Plays file in loop.
+  #
+  # Globals:
+  #     _CHANNELS (str) - Number of channels.
+  #     _FILENAME (str) - Name of music file.
+  #     _PLAYER (str) - Music player command.
+  #     _PLAYER_OPTIONS (str) - Music player command options.
+  #     _QUEUE_FILE (str) - Name of queue file.
+  #     _SAMPLERATE (str) - Sample rate.
+  #
+  # Arguments:
+  #     None.
+  #
+  # Returns:
+  #     String message or nothing.
+  #
+  aplay -t raw -c ${_CHANNELS} -f S16_LE -r ${_SAMPLERATE} ${_QUEUE_FILE} \
+    &> ${_QUEUE_FILE}.log &
 
-	aplay -t raw -c ${CHANNELS} -f S16_LE -r ${SAMPLERATE} ${QUEUE_FILE} \
-		&> ${QUEUE_FILE}.log &
+  echo 'Press <q> to exit, <space> to pause/play'
 
-	echo "Press <q> to exit, <space> to pause/play"
-
-	eval ${PLAYER} ${PLAYER_OPTIONS} ${file} >/dev/null 2>&1
+  ${_PLAYER} ${_PLAYER_OPTIONS} ${_FILENAME} >/dev/null 2>&1
 }
 
 
@@ -181,14 +217,14 @@ play() {
 #
 
 main() {
-	#
-	# Main program subroutine.
-	#
-	parse_args "$@"
-	make_queue queue=${QUEUE_FILE}
-	play file=${@: -1}  # filename is last argument
+  #
+  # Main program subroutine.
+  #
+  parse_args "$@"
+  make_queue
+  play
 
-	exit 0
+  exit 0
 }
 
 main "$@"
