issue #1

diff --git a/fplayer/fplayer b/fplayer/fplayer
--- a/fplayer/fplayer
+++ b/fplayer/fplayer
@@ -5,7 +5,7 @@
 #
 # https://github.com/macie/linux-shell-scripts
 #
-# Copyright (c) 2011-2013 Maciej Żok <maciek.zok@gmail.com>
+# Copyright (c) 2011-2014 Maciej Żok <maciek.zok@gmail.com>
 # MIT License (http://opensource.org/licenses/MIT)
 
 
@@ -22,20 +22,18 @@ show_help () {
 }
 
 
-VERSION="1.0"
+VERSION="1.1"
 PLAYER=mplayer
 PLAYER_OPTIONS=``
-PID=`ps x | awk 'match($0,/libflashplayer.so/){print $1}' | head -n 1`
-FD_ID=`lsof -p $PID | awk 'match($0,/Flash/){print $4}' | sed 's/[a-z]$//' | tail -1`
 
 
 while [[ $1 == -* ]]; do
 	case "$1" in
 		-h|--help|-\?) show_help; exit 0;;
 		-v|--version|-\?)
-			echo "fplayer "$VERSION;
+			echo "fplayer "${VERSION};
 			echo
-			echo "Copyright (c) 2013 Maciej Żok"
+			echo "Copyright (c) 2014 Maciej Żok"
 			echo "MIT License (http://opensource.org/licenses/MIT)"
 			exit 0;;
 		-p|--player) if (($# > 1)); then
@@ -55,5 +53,18 @@ while [[ $1 == -* ]]; do
 done
 
 
-$PLAYER $PLAYER_OPTIONS /proc/${PID}/fd/${FD_ID}
+PID=`ps x | awk 'match($0,/libflashplayer.so/)' | awk '!/awk match/{print $1}'`
 
+if [[ ${PID} != '' ]]; then
+	FD_ID=`lsof -p ${PID} | awk 'match($0,/Flash/){print $4}' | sed 's/[a-z]$//' | tail -1`
+else
+	echo "Error: no PID number (no open browser?)." 1>&2
+	exit 1;
+fi
+
+if [[ ${FD_ID} != '' ]]; then
+	${PLAYER} ${PLAYER_OPTIONS} /proc/${PID}/fd/${FD_ID}
+else
+	echo "Error: no FD number (no file in cache?)." 1>&2
+	exit 1;
+fi
