functions

diff --git a/fplayer/fplayer b/fplayer/fplayer
--- a/fplayer/fplayer
+++ b/fplayer/fplayer
@@ -1,7 +1,8 @@
 #!/bin/bash
 #
 # fplayer - watch last buffored flash movie (default in mplayer).
-#   inspired by Ivan Agarkov script (http://habrahabr.ru/blogs/linux/104420/#comment_3258122)
+#   inspired by Ivan Agarkov script
+#   (http://habrahabr.ru/blogs/linux/104420/#comment_3258122)
 #
 # https://github.com/macie/linux-shell-scripts
 #
@@ -9,7 +10,26 @@
 # MIT License (http://opensource.org/licenses/MIT)
 
 
-show_help () { 
+#
+#  DEFAULTS
+#
+
+VERSION="1.2"
+PLAYER=mplayer
+PLAYER_OPTIONS=``
+
+
+#
+#  MESSAGES
+#
+
+help_message () {
+	#
+	# Shows help message.
+	#
+	# Returns:
+	#     String message to standard output
+	#
 	echo "fplayer - watch last buffored flash movie (default in mplayer)."
 	echo "Usage:"
 	echo "  fplayer [options]"
@@ -17,54 +37,168 @@ show_help () {
 	echo "Options:"
 	echo "  -p, --player <command>          use specified player"
 	echo "  -o, --player-options <options>  set player options"
-	echo "  -h, --help                      show this help"
-	echo "  -v, --version                   show version number."
+	echo "  -h, --help                      show this help and exit"
+	echo "  -v, --version                   show version number and exit"
+}
+
+version_message() {
+	#
+	# Shows version message.
+	#
+	# Args:
+	#     version (str) - Version number.
+	#
+	# Returns:
+	#     String message to standard output
+	#
+	local version
+	local "${@}"
+
+	echo "fplayer "${version};
+	echo
+	echo "Copyright (c) 2014 Maciej Żok"
+	echo "MIT License (http://opensource.org/licenses/MIT)"
+}
+
+error_message() {
+	#
+	# Shows error message.
+	#
+	# Args:
+	#     msg (str) - Error message.
+	#
+	# Returns:
+	#     String message to err output.
+	#
+	local msg
+	local "${@}"
+
+	echo "Error: "${msg}"." 1>&2
 }
 
 
-VERSION="1.1"
-PLAYER=mplayer
-PLAYER_OPTIONS=``
+#
+#  FUNCTIONS
+#
+
+parse_args() {
+	#
+	# Parses script parameters.
+	#
+	# Args:
+	#     params (str) - Script params.
+	#
+	# Returns:
+	#     String message or nothing.
+	#
+	while [[ $1 == -* ]]; do
+		case "$1" in
+			-h|--help|-\?)
+				help_message
+				exit 0;;
+
+			-v|--version|-\?)
+				version_message version=${VERSION}
+				exit 0;;
+
+			-p|--player)
+				if (($# > 1)); then
+					PLAYER=$2
+					shift 2
+				else
+					error_message msg="no player specified"
+					exit 1
+				fi;;
+
+			-o|--player-options)
+				if (($# > 1)); then
+					PLAYER_OPTIONS=$2
+					shift 2
+				else
+					error_message msg="no player options specified"
+					exit 1
+			  	fi;;
+
+			-*)
+				error_message msg="invalid option: ${1}"
+				help_message
+				exit 1;;
+		esac
+	done
+}
+
+get_PID() {
+	#
+	# Retrives flash plugin PID.
+	#
+	# Returns:
+	#     PID number or exit (if no PID).
+	#
+	pid=`ps x | awk 'match($0,/libflashplayer.so/)' | \
+		awk '!/awk match/{print $1}'`
+
+	if [[ ${pid} != '' ]]; then
+		echo ${pid}
+	else
+		error_message msg="no PID number (no open browser?)"
+		exit 1
+	fi
+}
+
+get_FD() {
+	#
+	# Retrives FD id.
+	#
+	# Args:
+	#    pid (str) - flash plugin PID number
+	#
+	# Returns:
+	#     FD number or exit (if no FD).
+	#
+	local pid
+	local "${@}"
+
+	fd=`lsof -p ${pid} | awk 'match($0,/Flash/){print $4}' | sed 's/[a-z]$//'`
+
+	if [[ ${fd} != '' ]]; then
+		echo ${fd}
+	else
+		error_message msg="no FD number (no file in cache?)"
+		exit 1
+	fi
+}
+
+play() {
+	#
+	# Plays flash file from cache.
+	#
+	# Args:
+	#     fd (str) - FD number.
+	#     pid (str) - Flash plugin PID number.
+	#     player (str) - Movie player command.
+	#     options (str) - Movie player options.
+	#
+	local fd pid player options
+    local "${@}"
+
+	eval ${player} ${options} /proc/${pid}/fd/${fd}
+}
 
 
-while [[ $1 == -* ]]; do
-	case "$1" in
-		-h|--help|-\?) show_help; exit 0;;
-		-v|--version|-\?)
-			echo "fplayer "${VERSION};
-			echo
-			echo "Copyright (c) 2014 Maciej Żok"
-			echo "MIT License (http://opensource.org/licenses/MIT)"
-			exit 0;;
-		-p|--player) if (($# > 1)); then
-            PLAYER=$2; shift 2
-          else 
-            echo "Error: no player specified." 1>&2
-            exit 1
-          fi ;;
-		-o|--player-options) if (($# > 1)); then
-            PLAYER_OPTIONS=$2; shift 2
-          else 
-            echo "Error: no player options specified." 1>&2
-            exit 1
-          fi ;;
-		-*) echo "invalid option: $1" 1>&2; show_help; exit 1;;
-	esac
-done
+#
+#  MAIN ROUTINE
+#
 
+main() {
+	#
+	# Main program subroutine.
+	#
+	parse_args "$@"
+	get_PID pid
+	get_FD pid=${pid} fd
+	play player=${PLAYER} options=${PLAYER_OPTIONS} pid=${pid} fd=${fd}
 
-PID=`ps x | awk 'match($0,/libflashplayer.so/)' | awk '!/awk match/{print $1}'`
+	exit 0
+}
 
-if [[ ${PID} != '' ]]; then
-	FD_ID=`lsof -p ${PID} | awk 'match($0,/Flash/){print $4}' | sed 's/[a-z]$//' | tail -1`
-else
-	echo "Error: no PID number (no open browser?)." 1>&2
-	exit 1;
-fi
-
-if [[ ${FD_ID} != '' ]]; then
-	${PLAYER} ${PLAYER_OPTIONS} /proc/${PID}/fd/${FD_ID}
-else
-	echo "Error: no FD number (no file in cache?)." 1>&2
-	exit 1;
-fi
+main "$@"
diff --git a/lplayer/lplayer b/lplayer/lplayer
--- a/lplayer/lplayer
+++ b/lplayer/lplayer
@@ -5,24 +5,15 @@
 #
 # https://github.com/macie/linux-shell-scripts
 #
-# Copyright (c) 2011-2013 Maciej Żok <maciek.zok@gmail.com>
+# Copyright (c) 2011-2014 Maciej Żok <maciek.zok@gmail.com>
 # MIT License (http://opensource.org/licenses/MIT)
 
 
-show_help () { 
-	echo "lplayer - gapless loop player (using mplayer)."
-	echo "Usage:"
-	echo "  lplayer [options] filename"
-	echo 
-	echo "Options:"
-	echo "  -p, --playlist <filename>        use specified player"
-	echo "  -o, --player-options <options>   set player options"
-	echo "  -h, --help                       show this help"
-	echo "  -v, --version                    show version number."
-}
+#
+#  DEFAULTS
+#
 
-
-VERSION="1.0"
+VERSION="1.1"
 QUEUE_FILE=/tmp/lplayerqueue
 CHANNELS="2"
 SAMPLERATE="48000"
@@ -31,41 +22,173 @@ PLAYER_OPTIONS="-nocache -nolirc -vc null -vo null -loop 0 \
 -af resample=${SAMPLERATE} -ao pcm:nowaveheader:file=${QUEUE_FILE}"
 
 
-if [[ $# -eq 0 ]]; then
-	echo "Error: no audio file."
-	exit 1
-else
+#
+#  MESSAGES
+#
+
+help_message () { 
+	#
+	# Shows help message.
+	#
+	# Returns:
+	#     String message to standard output
+	#
+	echo "lplayer - gapless loop player (using mplayer)."
+	echo "Usage:"
+	echo "  lplayer [options] filename"
+	echo 
+	echo "Options:"
+	echo "  -p, --playlist <filename>        use specified player"
+	echo "  -o, --player-options <options>   set player options"
+	echo "      --channels <number>          set number of channels"
+	echo "      --samplerate <number>        set samplerate"
+	echo "  -h, --help                       show this help"
+	echo "  -v, --version                    show version number"
+}
+
+version_message() {
+	#
+	# Shows version message.
+	#
+	# Args:
+	#     version (str) - Version number.
+	#
+	# Returns:
+	#     String message to standard output
+	#
+	local version
+	local "${@}"
+
+	echo "lplayer "${version};
+	echo
+	echo "Copyright (c) 2013 Maciej Żok"
+	echo "MIT License (http://opensource.org/licenses/MIT)"
+}
+
+error_message() {
+	#
+	# Shows error message.
+	#
+	# Args:
+	#     msg (str) - Error message.
+	#
+	# Returns:
+	#     String message to err output.
+	#
+	local msg
+	local "${@}"
+
+	echo "Error: "${msg}"." 1>&2
+}
+
+
+#
+#  FUNCTIONS
+#
+
+parse_args() {
+	#
+	# Parses script parameters.
+	#
+	# Args:
+	#     params (str) - Script params.
+	#
+	# Returns:
+	#     String message or nothing.
+	#
+	if [[ $# -eq 0 ]]; then
+		error_message msg="no audio file"
+		exit 1
+	else
+		while [[ $1 == -* ]]; do
+			case "$1" in
+				-h|--help|-\?)
+					help_message
+					exit 0;;
+
+				-v|--version|-\?)
+					version_message version=${VERSION}
+					exit 0;;
+
+				-p|--playlist)
+					PLAYER_OPTIONS="${PLAYER_OPTIONS} -playlist"
+					shift 2;;
+
+				-o|--player-options) 
+					if [[ $# -gt 1 ]]; then
+						OPTIONS=${PLAYER_OPTIONS} $2
+						shift 2
+					else
+						error_message msg="no player options specified"
+						exit 1
+					fi;;
+
+				--channels)
+					CHANNELS=$2
+					shift 2;;
+
+				--samplerate)
+					SAMPLERATE=$2
+					shift 2;;
+
+				-*)
+					error_message msg="invalid option: ${1}"
+					help_message
+					exit 1;;
+			esac
+		done
+	fi
+}
+
+make_queue() {
+	#
+	# Creates new queue.
+	#
+	# Args:
+	#     queue (str) - Queue file name.
+	#
+	local queue
+	local "${@}"
+
+	[[ -e ${queue} ]] && rm ${queue}
+	mkfifo ${queue}
+}
+
+play() {
+	#
+	# Plays file in loop.
+	#
+	# Args:
+	#     file (str) - s.
+	#
+	# Returns:
+	#     String message or nothing.
+	#
+	local file
+	local "${@}"
+
+	aplay -t raw -c ${CHANNELS} -f S16_LE -r ${SAMPLERATE} ${QUEUE_FILE} \
+		&> ${QUEUE_FILE}.log &
+
 	echo "Press <q> to exit, <space> to pause/play"
-fi;
+
+	eval ${PLAYER} ${PLAYER_OPTIONS} ${file} >/dev/null 2>&1
+}
 
 
-while [[ $1 == -* ]]; do
-	case "$1" in
-		-h|--help|-\?)
-			show_help; exit 0;;
-		-v|--version|-\?)
-			echo "lplayer "$VERSION;
-			echo
-			echo "Copyright (c) 2013 Maciej Żok"
-			echo "MIT License (http://opensource.org/licenses/MIT)"
-			exit 0;;
-		-p|--playlist)
-			PLAYER_OPTIONS="${PLAYER_OPTIONS} -playlist";;
-		-o|--player-options) 
-			if [[ $# -gt 1 ]]; then
-				OPTIONS=${PLAYER_OPTIONS} $2; shift 2
-			else 
-				echo "Error: no player options specified." 1>&2
-				exit 1
-			fi ;;
-		-*) echo "Invalid option: $1" 1>&2; show_help; exit 1;;
-	esac
-done
+#
+#  MAIN ROUTINE
+#
 
+main() {
+	#
+	# Main program subroutine.
+	#
+	parse_args "$@"
+	make_queue queue=${QUEUE_FILE}
+	play file=${@: -1}  # filename is last argument
 
-[[ -e $QUEUE_FILE ]] && rm $QUEUE_FILE
-mkfifo $QUEUE_FILE
+	exit 0
+}
 
-aplay -t raw -c $CHANNELS -f S16_LE -r $SAMPLERATE $QUEUE_FILE \
- &> $QUEUE_FILE.log &
-$PLAYER $PLAYER_OPTIONS "$@" >/dev/null 2>&1
+main "$@"
